### PR TITLE
Use Arc<AtomicBool> instead of Cell<bool>

### PR DESCRIPTION
**Pull request by canadaduane**
I was trying to reference a `graphics::Image` inside an ECS (`hecs`) that expects components to be thread-safe. I think wrapping the dirty flag in an `Arc<AtomicBool>` instead of a `Cell<bool>` should fix the issue.

See https://github.com/Ralith/hecs/issues/38

### CODE REVIEW

**Comment by not-fl3** [comment]
Thanks for PR! Does it works with HECS now?  Let me know if there are some other things making live with hecs/specs too complicated

**Comment by canadaduane** [comment]
It compiles, yes, and tests check out, but I haven't quite brought my game to a place where I can show images and say "Yes, it works!" haha

**Comment by Ralith** [comment]
Are you sure `Arc` is what you wanted here? That will cause cloned `Image`s to share the same flag, which was not the case when `Cell<bool>` was used. A closer analog would be a naked `AtomicBool`.

**Comment by not-fl3** [comment]
Good point, thanks! 

I would like to remove `dirty_flag` at all - it was needed with previous implementation, but probably may be avoided with `miniquad`.

**Comment by canadaduane** [comment]
Hmm, that was my own ignorance as I followed the suggestion from the compiler. The problem without `Arc` is that naked `AtomicBool` can't be cloned (I guess).

**Comment by Ralith** [comment]
Yeah, you have to write `Clone` manually, since the compiler can't guess what memory ordering you want to use.

**Pull request merged**
