### PR TITLE
Implement DirtyFlag as naked AtomicBool

### PR DESCRIPTION
**Pull request by canadaduane**
This is an attempt at fixing the `Arc<AtomicBool>` work I did earlier. I believe this is more in-line with what @Ralith had in mind (see https://github.com/not-fl3/good-web-game/pull/23). The idea is that each thread would have its own dirty_filter rather than copying a reference counter to a single dirty_filter.

I took implementation hints from this rust-lang thread:
https://users.rust-lang.org/t/struct-with-atomic-fields-still-require-arc-and-clones/21348/2

### CODE REVIEW

**Comment by Ralith** [comment]
I'm not familiar with this code base so I can't speak to correctness in general, but this definitely is more closely analogous to the original `Cell<bool>`.

**Comment by not-fl3** [comment]
Thanks for PR! 

While this is not a blocker for you - I guess it works even with the Arc - let me check the possibility to remove `dirty_flag` completely.

**Comment by canadaduane** [comment]
Yeah, this isn't blocking me. Thanks.

**Comment by PSteinhaus** [comment]
This looks good, I'm merging it now. If we decide to remove the dirty flag entirely it probably doesn't matter much what it looks like and from what I've read this seems to be an improvement for now.

**Pull request merged**
